name: Daily Colab Run

on:
  schedule:
    - cron: "24 7 * * *"  # Chạy mỗi ngày vào lúc 03:40 UTC
  push:
  workflow_dispatch:

jobs:
  run_colab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -q -U pip
          pip install -q jupyterlab

      - name: Run Colab notebook
        run: |
          jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=600 test_Auto.ipynb

      - name: Commit and push if changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'vanquy03'
          git config --global user.email 'vanquy03@gmail.com'
          git add . 
          git commit -m "Auto-run Colab notebook" || echo "No changes to commit"
          git push https://vanquy03:${{ secrets.GH_PAT }}@github.com/QuyHoang7703/Test_connect_with_Colab.git || echo "No changes to push"
