name: Daily Colab Run

on:
  schedule:
    - cron: "40 3 * * *"  # Chạy mỗi ngày vào lúc 03:40 UTC
  push:
  workflow_dispatch:

jobs:
  run_colab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -q -U pip
          pip install -q jupyterlab

      - name: Run Colab notebook
        run: |
          jupyter nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute test_Auto.ipynb

      - name: Commit and push if changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'vanquy03'
          git config --global user.email 'vanquy03@gmail.com'
          git add .
          git commit -m "Auto-run Colab notebook" || echo "No changes to commit"
          git push || echo "No changes to push"
